[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#594400'

[colors.cursor]
text = '#131313'
cursor = '#eec148'

[colors.normal]
black   = '#131313'
red     = '#ff4c3b'
green   = '#60ee48'
yellow  = '#ffde3b'
blue    = '#e2ae24'
magenta = '#6e5000'
cyan    = '#eec148'
white   = '#f9f4e4'

[colors.bright]
black   = '#9a968a'
red     = '#ff8579'
green   = '#94ff82'
yellow  = '#ffea82'
blue    = '#ffd667'
magenta = '#ffdd82'
cyan    = '#ffe9ae'
white   = '#fffcf6'
