[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#584400'

[colors.cursor]
text = '#131313'
cursor = '#ecc248'

[colors.normal]
black   = '#131313'
red     = '#ff4d3c'
green   = '#5fec48'
yellow  = '#ffdf3c'
blue    = '#e0b025'
magenta = '#6d5100'
cyan    = '#ecc248'
white   = '#f7f2e3'

[colors.bright]
black   = '#999589'
red     = '#ff857a'
green   = '#94ff82'
yellow  = '#ffea82'
blue    = '#ffd868'
magenta = '#ffdf82'
cyan    = '#ffeaaf'
white   = '#fffcf6'
