
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃            Enviroment Configurationenv                      ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

env = HYPRCURSOR_SIZE,24
env = XCURSOR_SIZE,24
env = QT_CURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME_QT6,qt6ct
env = QT_QPA_PLATFORMTHEME,qt6ct
env = xx-color-management-v4,true
env = PROTON_ENABLE_WAYLAND,1
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_RENDERER_ALLOW_SOFTWARE,1


#envd = PROTON_ENABLE_WAYLAND,1
env = XDG_MENU_PREFIX,arch-

# NVIDIA things
env = PROTON_ENABLE_NVAPI,1
env = PROTON_FORCE_NVAPI,1
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_GSYNC_ALLOWED,1
env = __GL_VRR_ALLOWED, 1
env = PROTON_ENABLE_NGX_UPDATER,1
env = NGX_DLSS_SR_OVERRIDE,on
env = NGX_DLSS_RR_OVERRIDE,on
env = NGX_DLSS_FG_OVERRIDE,on
env = PROTON_ENABLE_NGX_UPDATER,1
env = DXVK_NVAPI_DRS_NGX_DLSS_SR_OVERRIDE,on
env = DXVK_NVAPI_DRS_NGX_DLSS_RR_OVERRIDE,on
env = DXVK_NVAPI_DRS_NGX_DLSS_FG_OVERRIDE,on
env = DXVK_NVAPI_DRS_NGX_DLSS_SR_OVERRIDE_RENDER_PRESET_SELECTION,render_preset_latest
env = DXVK_NVAPI_DRS_NGX_DLSS_RR_OVERRIDE_RENDER_PRESET_SELECTION,render_preset_latest
